require 'nokogiri'
require 'open-uri'
require 'colorize'
require 'pry'
require_relative '../lib/cli.rb'
require_relative '../lib/recipes.rb'
require_relative '../lib/scraper.rb'
require_relative '../lib/chef.rb'
